[package]
name = "neubar"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk4 = "0.7.3"
polodb_core = "4.4.0"
serde = "1.0.195"
symphonia = { version = "0.5.3", features = [ "all" ] }
